/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContactSection: typeof import('./src/components/ContactSection.vue')['default']
    Experience: typeof import('./src/components/Experience.vue')['default']
    Experince: typeof import('./src/components/Experince.vue')['default']
    FormComponent: typeof import('./src/components/formComponent.vue')['default']
    NavMenu: typeof import('./src/components/NavMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestButton: typeof import('./src/components/TestButton.vue')['default']
  }
}
